name: Maven Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with JDK ${{ matrix.java-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java-version: [ 8, 11, 17, 21 ]
    steps:
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run Maven Build
        # Suppress download messages by Slf4jMavenTransferListener,
        # see https://blogs.itemis.com/en/in-a-nutshell-removing-artifact-messages-from-maven-log-output
        run: mvn -B clean test "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
